Network/seogeurim
Seogeurim/CS-study pull request #20
Opened 2021-03-04 14:39 UTC by Seogeurim

### 변경 사항  

> Issue 참고 : [Note Status Check](https://github.com/Seogeurim/CS-study/issues/2)

1. OSI 7 계층 이론 정리
2. TCP 3-way-handshake & 4-way-handshake 이론 정리
3. HTTP 요청 방식 - GET, POST 이론 정리
4. HTTP 요청 방식 질의응답

### Point of discussion 

오타나 잘못된 부분이 있을 경우 언급 부탁드립니다 !

### Reference

2021-03-16 06:29 UTC, KimKwon approved these changes
핸드쉐이크 과정을 말로 잘 풀어서 설명해주셨네요 !

2021-03-16 06:29 UTC, KimKwon commented on contents/network/README.md
> +- 파일 : multipart/form-date
```suggestion
- 파일 : multipart/form-data
```

2021-03-18 15:24 UTC, Seogeurim commented on contents/network/README.md
> +- 파일 : multipart/form-date
감사합니당 ~~

2021-03-18 15:37 UTC, Seogeurim commented
@Hee-Jae 
> 오타를 발견했습니다.
> 현재의 인터넷은 TCP/IP 5계층 (Application-Transport-Network-Datalink-Physical) 모델을 기반으로 합니다.

이 부분 어디에 가면 제대로 볼 수 있을까요? ㅠㅠ 어디에서는 4계층이라 하고, 어디에서는 5계층이라고 하네용 ㅠㅠ !! 도움을 요청합니당 !!

2021-03-18 16:00 UTC, ggjae commented
저는 OSI 7 layer에서 최근 동향에 따라 계층구조가 점점 변해가고 있는거로 알고있습니다. 한번 변해진 tcp/ip protocol suite에 대해 찾아보세요!

2021-03-18 16:02 UTC, ggjae commented
4계층은 피지컬을 제외한 링크레이어부터 시작하는 internet protocol suite인 것 같고, 5계층은 피지컬, 데이터링크 - 로 이루어진 tcp/ip protocol suite인 것 같아요..!

2021-03-18 16:07 UTC, ggjae commented
@Seogeurim 찾았어요!!!

https://tools.ietf.org/html/rfc1122
RFC1122, RFC1123 공식문서에서는 link layer, IP layer, transport layer, application layer 네개로 나누고 있네요. 피지컬 레이어(1계층)을 링크 레이어로 묶어서 설명하는 듯 해요. 한번 확인해보세요!

2021-03-18 16:12 UTC, Seogeurim commented
@ggjae 
헐 우와 !! 역시 공식 문서로 찾아야 하는 거였네요 ! Internet Protocol Suite라는 이름으로 찾아야했구나 ㅠ 내일 한 번 읽어보고 공부한 뒤 업로드하겠습니다 !!!

2021-03-19 12:55 UTC, Hee-Jae commented
@ggjae 아.. 네트워크 강의때 5계층으로 배워서 무조건 5계층인줄 알았는데 공식문서에서 피지컬과 데이터링크를 묶어 놨군요... 새로 배워갑니다ㅎㅎ
@Seogeurim 널리 쓰이는 네트워크 전공 서적에서는 5계층으로 소개를 많이 해주던데 공식문서에서 4계층으로 분류를 하니 내용적인 면에서는 큰 오류는 없는 것 같아요. 내용 수정 안하셔도 될 것 같습니다.

2021-03-20 08:41 UTC, Hee-Jae approved these changes

2021-03-21 10:35 UTC, ggjae requested changes
잘 읽었습니다. 덕분에 네트워크를 다시 한번 되돌아봤어요.
살짝만 수정 부탁드립니다! 답변 돌아오는 즉시 approve 하겠습니다. 혹시라도 쉼표나 세세한 사항에서는 수정하지 않으셔도 괜찮습니다 (__)

2021-03-21 10:35 UTC, ggjae commented on contents/network/README.md
> +대한 규칙이 있어야 의사소통을 할 수 있을 것이다. 이 규칙을 정의한 것이 프로토콜이고, 이 규칙은 계층별로 다르게 존재한다.
```suggestion
위에서 프로토콜이 계층별로 구성된다고 언급하였다. 이 프로토콜이란 메시지를 주고 받는 양식이나 규칙을 의미하는 **통신 규약**이다.

시스템 간 메시지를 주고 받기 위해서는 한쪽에서 보낸 메시지를 반대쪽에서 이해할 수 있어야 한다. 한쪽에서 '안녕' 이라는 메시지를 보냈을 때 
인사로 알아듣고 대답으로 '안녕' 이라는 메시지를 보낼 수 있어야 한다는 뜻이다. 통신 모델에서도 메시지를 주고 받으며 통신할 때 그 언어와 대화 방법에 
대한 규칙이 있어야 의사소통을 할 수 있을 것이다. 이 규칙을 정의한 것이 프로토콜이고 이 규칙은 계층별로 다르게 존재한다.
```

저도 쉼표를 좋아해서 블로그를 작성하는데에 쉼표를 많이 작성했는데 여기서는 쉼표가 필요 없을 것 같아요!

2021-03-21 10:35 UTC, ggjae commented on contents/network/README.md
> +대한 규칙이 있어야 의사소통을 할 수 있을 것이다. 이 규칙을 정의한 것이 프로토콜이고, 이 규칙은 계층별로 다르게 존재한다.
사실 이 readme에 과도한 쉼표가 많아요! 하지만 가독성이 좋네요~

2021-03-21 10:35 UTC, ggjae commented on contents/network/README.md
> +
GET방식을 사용하는 예시도 들어가면 이해가 훨씬 편할 것 같아요! 위에 url address에서의 예시는 이름으로 되어있지만 우리가 실생활에서 접할 수 있는 것들 있잖아요! ex) https://google.com/search?q=서그림
'GET 방식은 캐싱을 사용할 수 있어'가 처음엔 어떤 캐싱인지 몰랐는데 저는 예제를 찾아보다가 이해가 훨씬 쉬워졌어요.
예를 들면 https://www.google.com/search?q=박재용 이라고 검색을 한번 하면? '박' 만 적어도 '박재용'이 캐시에 담겨있는 느낌이겠죠?

2021-03-21 10:35 UTC, ggjae commented on contents/network/README.md
> +      (ex. 게시판의 리스트, 게시글 보기 기능 | 예외. 방문자의 로그 남기기, 글을 읽은 횟수 증가 기능)
여기에 제가 위의 말한 example이 여기 있네요..! 예시들을 위에서 설명해줘도 괜찮을 것 같아요!

2021-03-21 13:04 UTC, Seogeurim commented on contents/network/README.md
> +대한 규칙이 있어야 의사소통을 할 수 있을 것이다. 이 규칙을 정의한 것이 프로토콜이고, 이 규칙은 계층별로 다르게 존재한다.
아 제가 공부하면서 써서 그른가 쉼표가 많네용 ㅎㅎㅎ 다 지워보겠습니당 ~! 감사해요 ~~

2021-03-21 13:21 UTC, Seogeurim commented on contents/network/README.md
> +
넹 예시를 넣는 것 엄청 좋은 것 같아요 ! 추가하겠습니당 !!
캐싱은 GET 해온 데이터가 캐시되는 것이라고 이해했는데, 설명한 이름 검색 예시는 요청 정보도 캐시가 되는 것인가요 ? 자세히 설명해주실 수 있나요 !!?

2021-03-21 13:40 UTC, ggjae commented on contents/network/README.md
> +
제가 말한 건 쿠키인 것 같아요. 그림님이 이해하신게 정확합니다! 예시를 잘못 얘기해드렸네요!!

2021-03-22 05:10 UTC, Seogeurim commented on contents/network/README.md
> +
넹 ~~~ !

2021-03-22 05:10 UTC, Seogeurim commented
@ggjae 다 수정해서 커밋했습니당 어푸룹 주세요 ~~~

2021-03-22 11:02 UTC, ggjae approved these changes

2021-03-22 11:08 UTC, merged

2021-03-25 08:12 UTC, KimKwon commented
Seogeurim: 이론*3 + 질의응답1  = +50
ggjae, Hee-Jae, KimKwon: Pr리뷰 각각 +5