OperatingSystem/seogeurim
Seogeurim/CS-study pull request #38
Opened 2021-05-11 16:51 UTC by Seogeurim

### 변경 사항  

> Issue 참고 : [Note Status Check](https://github.com/Seogeurim/CS-study/issues/2)

1. 프로세스 상태
2. 스케줄링 알고리즘

### Point of discussion 

OS 관련 정리 보충해보았습니다 ! 앞으로도 계속 쭉쭉 할 예정인데 미리 올려봅니다 ㅎㅎ

### Reference 

공룡책 10판

2021-05-16 06:42 UTC, Hee-Jae commented on contents/operating-system/README.md
> +- **Running** : Instruction이 실행됨
다른 상태들은 '프로세스'로 설명됐는데 이 부분만 'Instruction'으로 설명이 되네요. '프로세스가 생성됨' 이라고 하는게 더 이해하기 쉬울 것 같아요.

2021-05-16 07:06 UTC, ggjae requested changes
잘 읽었습니다 (__)

2021-05-16 07:06 UTC, ggjae commented on contents/operating-system/README.md
> +위와 같이 RR 알고리즘의 성능은 time quantum의 크기에 좌우될 수 있으므로 적절히 선정해야 하며, 이는 context-switch time보다 큰 것이 좋으며, 또 너무 커서는 안 된다. (경험적으로 CPU burst의 80프로는 time quantum보다 짧은게 좋다고 함)
그림씨의 쉼표 스타일이 아직 남아있네요 ㅎㅎㅎ 너무 잘 봤습니다~!
' 위와 같이 RR 알고리즘의 성능은 time quantum의 크기에 좌우될 수 있으므로 적절히 선정해야 하며 이는 context-switch time보다 큰 것이 좋지만 또 너무 커서는 안 된다. (경험적으로 CPU burst의 80프로는 time quantum보다 짧은게 좋다고 함)'

2021-05-17 13:33 UTC, Seogeurim commented on contents/operating-system/README.md
> +- **Running** : Instruction이 실행됨
![image](https://user-images.githubusercontent.com/22045163/118497095-b7e5d100-b75f-11eb-80c2-6de8b79d77a8.png)

공룡책에 이렇게 표시가 되어있는데, 그러면 '프로세스의 Instruction이 실행됨' 으로 하는 것이 더 이해하기 쉽고 정확하려나요? 아니면 상관 없이 그냥 '프로세스가 실행됨'으로 해도 될까요?

2021-05-17 13:33 UTC, Seogeurim commented on contents/operating-system/README.md
> +위와 같이 RR 알고리즘의 성능은 time quantum의 크기에 좌우될 수 있으므로 적절히 선정해야 하며, 이는 context-switch time보다 큰 것이 좋으며, 또 너무 커서는 안 된다. (경험적으로 CPU burst의 80프로는 time quantum보다 짧은게 좋다고 함)
아차 ! 또 쉼표를 ㅎㅎㅎ 전보다 훨씬 의식하며 쓰는데도 남아있네용 ㅎㅎ 고치겠습니당 ~!

2021-05-23 04:41 UTC, Hee-Jae commented on contents/operating-system/README.md
> +- **Running** : Instruction이 실행됨
다시 생각해보니 '프로세스가 실행됨' 이라고 하면 프로세스가 메모리에 적재된 이후 New 상태부터 Terminated 상태까지를 모두 통틀어 '프로세스가 실행되었다.' 라고 볼 수도 있겠네요. 공룡책에서는 정확히 프로세스 내의 Instruction들이 실행 됨을 알려주려고 저렇게 표기한 것 같아요.  독자분들에게 이해하기 쉽게 보여드리기 위해서라면 '프로세스의 Instruction이 실행됨' 으로 하는게 맞겠어요.

2021-05-23 07:05 UTC, yoongoing approved these changes

2021-05-23 11:30 UTC, Seogeurim commented on contents/operating-system/README.md
> +- **Running** : Instruction이 실행됨
그르네요 ! 이렇게 풀어서 설명해보니까 확실히 개념이 잡히네요 감사합니다. 프로세스의 Instruction이 실행됨으로 고쳐서 커밋하겠습니당 ㅎㅎ

2021-05-23 11:46 UTC, Hee-Jae approved these changes

2021-05-23 12:03 UTC, KimKwon approved these changes
운영체제 개념은 확실히 하고 가는게 좋은 것 같습니다 👍

2021-05-23 12:03 UTC, KimKwon approved these changes

2021-05-23 12:03 UTC, KimKwon commented on contents/operating-system/README.md
> +- 문제점) **indefinit blocking**, **starvation**
```suggestion
- 문제점) **indefinite blocking**, **starvation**
```

2021-05-24 17:28 UTC, Seogeurim commented on contents/operating-system/README.md
> +- 문제점) **indefinit blocking**, **starvation**
감사합니당 ㅎㅎ 👍🏻

2021-05-24 17:28 UTC, Seogeurim commented
@ggjae 변경 요청 사항 반영했어요 ! 어푸룹 부탁드립니당 ㅎㅎ

2021-05-25 09:10 UTC, ggjae approved these changes

2021-05-25 09:10 UTC, merged

2021-05-25 09:11 UTC, ggjae commented on contents/operating-system/README.md
> +위와 같이 RR 알고리즘의 성능은 time quantum의 크기에 좌우될 수 있으므로 적절히 선정해야 하며, 이는 context-switch time보다 큰 것이 좋으며, 또 너무 커서는 안 된다. (경험적으로 CPU burst의 80프로는 time quantum보다 짧은게 좋다고 함)
ㅎㅎㅎ 좋습니다!!!

2021-06-05 16:29 UTC, KimKwon commented
Seogeurim: + 15
Hee-Jae, ggjae, kimkwon: +5