Design pattern/heejae
Seogeurim/CS-study pull request #45
Opened 2021-07-08 14:00 UTC by Hee-Jae

### 변경 사항  

> Issue 참고 : [Note Status Check](https://github.com/Seogeurim/CS-study/issues/2)

1. MVC 패턴 정리
2. MVC 패턴 코드 추가
3. 싱글톤 파이썬 코드 'SingletonPython' 디렉토리로 이동
### Point of discussion 
오랜만에 올리는 PR이네요. 질문, 피드백 환영합니다^^
### Reference

2021-07-09 07:44 UTC, ggjae requested changes
기본적인 MVC에 대해서 다시 한번 알게 되었고, 예시 코드를 통해 이해하니 확실히 좋네요! 글을 흥미롭게 읽던 도중에 오타 하나 발견하여 먼저 오타만 Request Changes 보내 봅니다!

2021-07-09 07:44 UTC, ggjae commented on contents/design-pattern/mvc-python.md
> +> 그렇지 않다. 웹사이트가 MVC를 설명하기 가장 조흔 예다. MVC 패턴은 GUI기반 애플리케이션이나 프로그램 내 요소 간의 높은 독립성이 요구되는 경우 적합하다. 블로그나 영화 데이터베이스 애플리케이션, 비디오 스트리밍 애플리케이션 등이 MVC가 적합한 전형적인 예다. 하지만 MVC가 아무리 좋다 해도 랜딩 페이지나 마케팅 콘텐츠, 단일 페이지 애플
글이 너무 조흐네요. 175번째 line 오타 수정 부탁드립니다! ^^7

2021-07-09 09:03 UTC, Hee-Jae commented on contents/design-pattern/mvc-python.md
> +> 그렇지 않다. 웹사이트가 MVC를 설명하기 가장 조흔 예다. MVC 패턴은 GUI기반 애플리케이션이나 프로그램 내 요소 간의 높은 독립성이 요구되는 경우 적합하다. 블로그나 영화 데이터베이스 애플리케이션, 비디오 스트리밍 애플리케이션 등이 MVC가 적합한 전형적인 예다. 하지만 MVC가 아무리 좋다 해도 랜딩 페이지나 마케팅 콘텐츠, 단일 페이지 애플
오타 발견 감사합니다^^ 바로 수정했습니다.

2021-07-11 14:51 UTC, yoongoing approved these changes
오 이 내용 필요했어요. 코드와 함께 올려주셔서 더 잘 이해했습니다~

2021-07-11 16:50 UTC, Seogeurim reviewed
몇가지 궁금한 점들을 코멘트 달아보았습니다 !! 덕분에 조금은 모호하게 알고 있었던 MVC 패턴 관련해서 상세하게 공부할 수 있었던 좋은 시간이었습니다 ㅎㅎ

2021-07-11 16:50 UTC, Seogeurim commented on contents/design-pattern/mvc-python.md
> +### 모든 클래스를 구현한 코드 예시
여기서 '모든 클래스를 구현한 코드' 라는게 어떤 의미인가요?

2021-07-11 16:50 UTC, Seogeurim commented on contents/design-pattern/mvc-python.md
> +5. 플랫폼 개발자와 UI 개발자 같이 특정 분야의 전문가들이 독립적으로 일할 수 있는 환경을 제공한다.
MVC 패턴의 장점은 무엇이고 단점은 무엇인지, 단점이 있다면 대안은 없는지 등이 중요할 것 같아 찾아보았습니다.

우선 장점은 적어주신 것처럼 백엔드/프론트엔드가 분리되는 것, 모델이 독립성을 가지는 것, 유연하고 확장이 용이한 구조를 가진다는 것입니다. 

하지만 단점은 복잡한 구조로 보일 수 있으며, Model과 View의 완벽한 분리가 어렵다는 것입니다.
- 복잡한 구조로 보인다 -> 설계 시간이 오래 걸리고 숙련된 개발자가 필요하다.
- Model과 View의 완벽한 분리가 어렵다 -> 어플리케이션 규모가 커질수록 다수의 View와 Model을 가지게 될 것. 이 때, 하나의 View에 연결되는 Model이 여러 개로 늘어난다면 Controller에 다수의 Model과 View가 복잡하게 연결되게 되고, 그 결과 MVC가 너무 복잡해져 코드 분석/수정/테스트가 힘들어진다. 이것을 MVC의 한계라 부르고 'Massive ViewController' 라는 용어도 있다고.
- 양방향 바인딩 -> Model 업데이트 <-> View 업데이트의 양방향 바인딩. 복잡도가 커진다면 위험성이 커진다.
- Controller의 크기가 커진다 -> 통신이나 View의 생명주기에 관한 코드를 모두 Controller에서 다루게 되면서 그 크기가 지나치게 커지는 경향이 있다.

이러한 단점을 극복할 수 있는 대안으로
MVP, MVVM, Viper, Clean Architecture, Flux, Redux, RxMVVM…. 등의 다양한 패턴이 파생되었다고 합니다.

MVP, MVVM의 경우 Model과 View의 완벽한 분리가 이루어질 수 있으면서 MVC의 장점을 가지고 있습니다. 짧게 정리해보면
- MVP : Model + View + Presenter
  - Model : 데이터와 비즈니스 로직 / View : UI / Presenter : View에서 요청한 정보로 Model을 가공하여 View에 전달
  - View : Presenter = 1 : 1 관계
  - View와 Model의 의존성이 해결되었지만, View와 Presenter 사이의 의존성은 높아진다는 단점
- MVVM : Model + View + View Model
  - Model : 데이터와 비즈니스 로직 / View : UI / View Model : View를 위한 Model
  - View : View Model = 1 : n 관계
  - Command 패턴(요청을 캡슐화) + Data Binding 패턴(Model-UI 사이 싱크 맞춰주는 것)
  - View와 Model, View와 View Model 사이의 의존성이 없음, 단점은 View Model의 설계가 쉽지 않다는 점

> Reference
> - [[아키텍처 패턴] MVC 패턴이란?](https://medium.com/@jang.wangsu/%EB%94%94%EC%9E%90%EC%9D%B8%ED%8C%A8%ED%84%B4-mvc-%ED%8C%A8%ED%84%B4%EC%9D%B4%EB%9E%80-1d74fac6e256)
> - [MVC패턴](https://woongsios.tistory.com/37)
> - [[디자인패턴] MVC, MVP, MVVM 비교](https://beomy.tistory.com/43)
> - [🙈[디자인패턴] 커맨드 패턴 ( Command Pattern )🐵](https://victorydntmd.tistory.com/295)

2021-07-11 16:50 UTC, Seogeurim commented on contents/design-pattern/mvc-python.md
> +> 컴파운드 패턴은 더 큰 문제를 해결하기 위해 여러 패턴을 합친 것이다. MVC 패턴은 가장 많이 쓰이는 컴파운드 패턴이다. 안정적이며 많이 쓰이기 때문에 개별적인 패턴처럼 취급된다.
그럼 MVC는 어떤 패턴들을 합친 것인지 궁금합니다 !

2021-07-11 16:50 UTC, Seogeurim commented on contents/design-pattern/mvc-python.md
> +> 그렇지 않다. 웹사이트가 MVC를 설명하기 가장 좋은 예다. MVC 패턴은 GUI기반 애플리케이션이나 프로그램 내 요소 간의 높은 독립성이 요구되는 경우 적합하다. 블로그나 영화 데이터베이스 애플리케이션, 비디오 스트리밍 애플리케이션 등이 MVC가 적합한 전형적인 예다. 하지만 MVC가 아무리 좋다 해도 랜딩 페이지나 마케팅 콘텐츠, 단일 페이지 애플
랜딩 페이지, 마케팅 콘텐츠, 단일 페이지 어플리케이션에 쓰는 것이 적합하지 않은 이유는 무엇인가요?

2021-07-11 17:56 UTC, KimKwon approved these changes
패턴 관련 지식은 배워도배워도 끝이 없네요
MVC에 대해 정말 오랜만에 학습하고 갑니다^_^

2021-07-12 02:01 UTC, Hee-Jae commented on contents/design-pattern/mvc-python.md
> +### 모든 클래스를 구현한 코드 예시
MVC에는 기본적으로 Model 클래스, View 클래스, Controller 클래스가 있고 이  세 개의 클래스가 서로 상호작용 하며 동작합니다. 이 모든 클래스를 예시로 구현한 코드라는 뜻입니다. 그리고 MVC구조로 만들어진 프로그램을 사용하는 클라이언트의 예시로 Client 클래스도 구현을 해본 것입니다.

2021-07-12 02:04 UTC, Hee-Jae commented on contents/design-pattern/mvc-python.md
> +5. 플랫폼 개발자와 UI 개발자 같이 특정 분야의 전문가들이 독립적으로 일할 수 있는 환경을 제공한다.
엄청난 자료를 남겨주셨네요.. MVC의 단점과 MVP, MVVM에 대해서 더 공부해보고 남겨주신 자료 참고해서 추후에 새로 업데이트 하겠습니다.

2021-07-12 02:09 UTC, Hee-Jae commented on contents/design-pattern/mvc-python.md
> +> 컴파운드 패턴은 더 큰 문제를 해결하기 위해 여러 패턴을 합친 것이다. MVC 패턴은 가장 많이 쓰이는 컴파운드 패턴이다. 안정적이며 많이 쓰이기 때문에 개별적인 패턴처럼 취급된다.
인터넷에서 참고할 만한 좋은 자료 찾아서 공유 해봅니다.
출처 : https://sgc109.github.io/2020/07/18/compound-pattern-feat-mvc/

> MVC 는 Model-View-Controller 의 약자로서, 역할에 따라 3개의 컴포넌트로 분리하고
> 여러 디자인 패턴을 적용하여 재사용성을 높인 대표적인 컴파운드 패턴의 예다.
> 그렇다면 MVC 패턴에서 사용된다는 여러 디자인 패턴은 대체 무엇일까?
> 전통적인 MVC 패턴에서는 다음 3가지 패턴이 사용된다.

> - 옵저버(Observer) 패턴[1]
> Model 의 상태가 변경 되었을 때 Controller, 혹은 View 에게 이 사실을 알리는데 사용된다.
> - 컴포지트(Composite) 패턴[2]
> View 를 구성하는 컴포넌트들은 계층 구조를 이룬다. (e.g. Java Swing 의 JFrame/JLabel 등, Android 의 View/ViewGroup, HTML 의 DOM)
> - 스트래티지(Strategy) 패턴[3]
> Controller 의 핵심 기능을 인터페이스로 분리하여 View 가 이 인터페이스를 통해 Controller 를 구성(Composition) 한다. 그렇기 때문에 View 는 Controller 를 갈아 끼우며 기능을 변경할 수 있다.
> - 또한, 필요에 따라 어댑터(Adapter) 패턴[4] 을 함께 사용할 수도 있다.

2021-07-12 02:16 UTC, Hee-Jae commented on contents/design-pattern/mvc-python.md
> +> 그렇지 않다. 웹사이트가 MVC를 설명하기 가장 좋은 예다. MVC 패턴은 GUI기반 애플리케이션이나 프로그램 내 요소 간의 높은 독립성이 요구되는 경우 적합하다. 블로그나 영화 데이터베이스 애플리케이션, 비디오 스트리밍 애플리케이션 등이 MVC가 적합한 전형적인 예다. 하지만 MVC가 아무리 좋다 해도 랜딩 페이지나 마케팅 콘텐츠, 단일 페이지 애플
음.. 이 부분에 대해서는 깊이 있게 알아보지는 않았지만 제 생각에는 "굳이" 라는 이유 때문인 것 같습니다. 웹 페이지의 파일 구조가 매우 단순하거나 보여주기를 위한 용도로 사용되는 웹페이지의 경우에는 굳이 MVC를 이용하지 않아도 됩니다. 정말 단순한 웹에 모델, 뷰, 컨트롤러 클래스를 구현해서 분리해 놓는 것이 반드시 효율적이라고 볼 수는 없습니다.

2021-07-12 07:51 UTC, ggjae approved these changes
잘 보았습니다! 잘 수정해주셔서 감사해요 :)

2021-07-12 07:53 UTC, ggjae commented on contents/design-pattern/mvc-python.md
> +> 컴파운드 패턴은 더 큰 문제를 해결하기 위해 여러 패턴을 합친 것이다. MVC 패턴은 가장 많이 쓰이는 컴파운드 패턴이다. 안정적이며 많이 쓰이기 때문에 개별적인 패턴처럼 취급된다.
이 여러개의 패턴들이 정보처리기사 시험에 나오는 것으로 알고 있습니다! 알아두면 좋을 것 같네요. ㅎㅎㅎ 공부하다가 본 기억이 나서 댓글남기고 도망갑니다 슝슝 =3

2021-07-12 09:20 UTC, Hee-Jae commented on contents/design-pattern/README.md
> +- [MVC (Model-View-Controller)](mvc-python.md)
좋은 생각이네요. 바로 반영 했습니다^^

2021-07-12 14:21 UTC, Seogeurim commented on contents/design-pattern/mvc-python.md
> +### 모든 클래스를 구현한 코드 예시
아하 !! 그런 의미였군요 ! 네 이해했습니다 !! ㅎㅎㅎ

2021-07-12 14:23 UTC, Seogeurim commented on contents/design-pattern/mvc-python.md
> +> 컴파운드 패턴은 더 큰 문제를 해결하기 위해 여러 패턴을 합친 것이다. MVC 패턴은 가장 많이 쓰이는 컴파운드 패턴이다. 안정적이며 많이 쓰이기 때문에 개별적인 패턴처럼 취급된다.
아 !! 완전 이해했습니다 알아가야할 패턴들이 많네요 ㅎㅎ 이 부분 짧게 글에 덧붙이면 어떨까요?

2021-07-12 14:28 UTC, Seogeurim commented on contents/design-pattern/mvc-python.md
> +> 그렇지 않다. 웹사이트가 MVC를 설명하기 가장 좋은 예다. MVC 패턴은 GUI기반 애플리케이션이나 프로그램 내 요소 간의 높은 독립성이 요구되는 경우 적합하다. 블로그나 영화 데이터베이스 애플리케이션, 비디오 스트리밍 애플리케이션 등이 MVC가 적합한 전형적인 예다. 하지만 MVC가 아무리 좋다 해도 랜딩 페이지나 마케팅 콘텐츠, 단일 페이지 애플
아 ! 이해했습니다. MVC의 단점이 설계에 시간이 걸린다, 전문가가 필요하다 등이기 때문에 정말 단순하고 작은 규모의 어플리케이션에는 쓸 필요가 없고 그 예로 위 어플리케이션들이 있는거군요 ! 감사합니다 ㅎㅎ

2021-07-13 03:59 UTC, wntjq68 approved these changes
다들 MVC패턴에 관심이 많네요 ㅋㅋㅋㅋ코멘트 수가 ㄷㄷ,,, 의견 계속 반영하시느라 고생하셨어요 ㅎㅎ

2021-07-13 15:20 UTC, Hee-Jae commented on contents/design-pattern/mvc-python.md
> +> 컴파운드 패턴은 더 큰 문제를 해결하기 위해 여러 패턴을 합친 것이다. MVC 패턴은 가장 많이 쓰이는 컴파운드 패턴이다. 안정적이며 많이 쓰이기 때문에 개별적인 패턴처럼 취급된다.
해당 질문 하단에 꼬리질문으로 추가했습니다^^

2021-07-13 15:39 UTC, Seogeurim approved these changes
드디어 어푸루부 !

2021-07-13 15:39 UTC, Seogeurim commented on contents/design-pattern/mvc-python.md
> +> 컴파운드 패턴은 더 큰 문제를 해결하기 위해 여러 패턴을 합친 것이다. MVC 패턴은 가장 많이 쓰이는 컴파운드 패턴이다. 안정적이며 많이 쓰이기 때문에 개별적인 패턴처럼 취급된다.
확인했습니다 !! ㅎㅎ 수고하셨습니당 ~!

2021-07-13 15:39 UTC, merged