Os/yoongoing
Seogeurim/CS-study pull request #53
Opened 2021-07-18 01:56 UTC by yoongoing

### 변경 사항  

1. 캐시란?
2. 교착상태란?

> Issue 참고 : [Note Status Check](https://github.com/Seogeurim/CS-study/issues/2)

### Point of discussion 

여러가지 래퍼런스를 보며 정리했습니다. 공부하며 부족한 부분이 있을 경우, 댓글 남겨주세요

### Reference 

리드미에 기재해뒀습니다.

2021-07-18 05:18 UTC, wntjq68 approved these changes
캐시와 교착상태,,, OS에서 빠질 수 없는 중요한 내용들이네요~ 로컬 캐시랑 글로벌 캐시로 또 나눌 수 있는건 처음 알았네요~ 중요한 내용들 한번더 복습 하고 갑니다 !

2021-07-18 05:48 UTC, Hee-Jae approved these changes
운영체제 시간에 배운 내용들을 요약된 형태로 정리 해주셔서 예전에 배운 내용을 금방 복습해 볼 수 있었습니다^^

2021-07-18 09:20 UTC, ggjae requested changes
오랜만에 운영체제 이야기를 보니 흥미롭네요. 헌데 Circular wait을 '환형 대기'라고도 하나요? 오타인 줄 알았는데, 어떤 책에서는 환형 대기라고 할 수 있겠다고 생각이 드네요. 사실 영어에 대한 해석을 하는것이니..ㅎㅎㅎ :)

2021-07-18 09:20 UTC, ggjae commented on contents/operating-system/README.md
> +캐시란, 자주 사용하는 데이터나 값을 미리 복사해 놓는 임시 장소를 가리킨다. 캐시는 저장 공간이 작고 비용이 바싼대신, 데이터를 미리 복사해 놓기 때문에 계산이나 접근 시간 없이 더 빠른 속도로 데이터에 접근할 수 있다.
'바싼대신,' 오타 수정 부탁드립니다.

2021-07-18 09:20 UTC, ggjae commented on contents/operating-system/README.md
> +캐시란, 자주 사용하는 데이터나 값을 미리 복사해 놓는 임시 장소를 가리킨다. 캐시는 저장 공간이 작고 비용이 바싼대신, 데이터를 미리 복사해 놓기 때문에 계산이나 접근 시간 없이 더 빠른 속도로 데이터에 접근할 수 있다.
계산이나 접근하는 시간이 아예 없나요...?

2021-07-18 09:20 UTC, ggjae commented on contents/operating-system/README.md
> +4. **환형 대기(Circular Wait)** : 공유자원을 사용하기 위해 대기하는 프로세스들이 원형으로 구성되어 있고, 자신에게 할당된 자원을 점유하면서 앞이나 뒤 프로세스의 자원을 요구해야 한다.
'환형 대기'가 아닌 '순환형 대기' 이지 않나요? '환형 대기'라고도 하나...?

2021-07-18 09:51 UTC, KimKwon commented on contents/operating-system/README.md
> +4. **환형 대기(Circular Wait)** : 공유자원을 사용하기 위해 대기하는 프로세스들이 원형으로 구성되어 있고, 자신에게 할당된 자원을 점유하면서 앞이나 뒤 프로세스의 자원을 요구해야 한다.
보통 환형 대기라고 하지않나요? 의미적으로 서로 순환적인 구조로 자원을 요청하긴 하죠

2021-07-18 09:56 UTC, KimKwon requested changes
정리하느라 고생하셨습니다:)
캐시는 근본이죠

2021-07-18 09:56 UTC, KimKwon commented on contents/operating-system/README.md
> +CPU에서 명령어를 수행하며 매번 캐시 메모리를 참조하게 되는데, 이때 Hit률이 지역성을 갖는다.
```suggestion
CPU에서 명령어를 수행하며 매번 캐시 메모리를 참조하게 되는데, 이때 Hit rate가 지역성을 갖는다.
```

2021-07-18 10:00 UTC, KimKwon approved these changes

2021-07-19 11:18 UTC, yoongoing commented on contents/operating-system/README.md
> +캐시란, 자주 사용하는 데이터나 값을 미리 복사해 놓는 임시 장소를 가리킨다. 캐시는 저장 공간이 작고 비용이 바싼대신, 데이터를 미리 복사해 놓기 때문에 계산이나 접근 시간 없이 더 빠른 속도로 데이터에 접근할 수 있다.
+ 오타 수정 하겠습니다.
+ 아에 없다기 보단, 직접 메모리까지 안가도 되니 '훨씬 빠른속도'로 해석하면 될것 같네요. 수정하겠습니다~

2021-07-19 11:18 UTC, yoongoing commented on contents/operating-system/README.md
> +4. **환형 대기(Circular Wait)** : 공유자원을 사용하기 위해 대기하는 프로세스들이 원형으로 구성되어 있고, 자신에게 할당된 자원을 점유하면서 앞이나 뒤 프로세스의 자원을 요구해야 한다.
흠 둘다 비슷한 말이니 한글보다는 Circular Wait에 초점을 맞추죠!

2021-07-19 11:19 UTC, yoongoing commented on contents/operating-system/README.md
> +CPU에서 명령어를 수행하며 매번 캐시 메모리를 참조하게 되는데, 이때 Hit률이 지역성을 갖는다.
근본 맞쬬~ 수정하겠습니다.

2021-07-19 12:07 UTC, Seogeurim reviewed
캐시와 교착상태까지 많은 내용 정리하시느라 수고하셨습니다 !! 오랜만에 os 글 보면서 지식 구멍을 채웠네요 ㅠ 좋은 글 감사합니다 :)

2021-07-19 12:07 UTC, Seogeurim commented on contents/operating-system/README.md
> +시스템에 교착상태가 발생했는지 점검하여 교착상태에 있는 프로세스와 자원을 발견하는 기법이다.
교착상태에 있는 프로세스와 자원을 발견한 후에는 어떻게 처리하나요?

2021-07-20 08:26 UTC, yoongoing commented on contents/operating-system/README.md
> +교착상태가 발생할 가능성을 배제하지 않고, 교착상태가 발생하면 적절히 피해나가는 방법으로, **은행원 알고리즘(Banker's Algorithm)**이 사용된다.
오타 수정하겠습니다~

2021-07-20 08:27 UTC, yoongoing commented on contents/operating-system/README.md
> +- **기아 상태** : 계속해서 특정 프로세스의 자원을 강제로 방출시켜 선점을 시켜주면, 그 프로세스는 계속해서 희생자가 될 확률이 높아지고, 영원히 실행이 완료되지 못하는 기아상태에 빠질 수 있다. 따라서 **프로세스가 한정된 시간에만 희생자로 선정된다는 것을 반드시 보장해야한다.**
네 그런식으로 저도 이해했어요. 한 프로세스가 희생자가 될 시간을 한정한다는 소리입니다.

2021-07-20 08:28 UTC, yoongoing commented on contents/operating-system/README.md
> +- **기아 상태** : 계속해서 특정 프로세스의 자원을 강제로 방출시켜 선점을 시켜주면, 그 프로세스는 계속해서 희생자가 될 확률이 높아지고, 영원히 실행이 완료되지 못하는 기아상태에 빠질 수 있다. 따라서 **프로세스가 한정된 시간에만 희생자로 선정된다는 것을 반드시 보장해야한다.**
오 근데 몇분 이렇게 지정하는것 까지는 구체적으로 모르겠네요

2021-07-20 08:40 UTC, Seogeurim commented on contents/operating-system/README.md
> +- **기아 상태** : 계속해서 특정 프로세스의 자원을 강제로 방출시켜 선점을 시켜주면, 그 프로세스는 계속해서 희생자가 될 확률이 높아지고, 영원히 실행이 완료되지 못하는 기아상태에 빠질 수 있다. 따라서 **프로세스가 한정된 시간에만 희생자로 선정된다는 것을 반드시 보장해야한다.**
아하 알겠습니다 감사합니당 ~~

2021-07-20 08:41 UTC, Seogeurim approved these changes
수정 사항 확인했습니다 !!

2021-07-20 08:42 UTC, ggjae commented on contents/operating-system/README.md
> +4. **환형 대기(Circular Wait)** : 공유자원을 사용하기 위해 대기하는 프로세스들이 원형으로 구성되어 있고, 자신에게 할당된 자원을 점유하면서 앞이나 뒤 프로세스의 자원을 요구해야 한다.
네에 잘 보았습니다 :)

2021-07-20 08:43 UTC, ggjae approved these changes
고생하셨습니다 :)

2021-07-20 08:47 UTC, merged