[OS] 깃 정리
Seogeurim/CS-study pull request #56
Opened 2021-07-24 02:39 UTC by yoongoing

### 변경 사항  

1. 가상 메모리
2. 페이지 교체 알고리즘
3. 
> Issue 참고 : [Note Status Check](https://github.com/Seogeurim/CS-study/issues/2)

### Point of discussion 

아직 수정중이며, 중요한 내용들만 적어놨습니다! 지적/ 비판 좋아요

### Reference 

리드미에 기재해뒀습니다

2021-07-25 06:35 UTC, ggjae requested changes
잘 읽었습니다~~ :)

2021-07-25 06:35 UTC, ggjae commented on contents/operating-system/README.md
> +메인 메모리의 크기가 한정되어 있기때문에, 물리적인 메모리 크기보다 큰 프로세스를 실행시킬 수 없다. 그렇다면 메인 메모리보다 크기가 큰 프로세스를 실행시키고 싶으면 어떻게 해야 할까? 그래서 나온 방법이 바로 '가상메모리'이다.
있기때문에, 물리적인 => 있기 때문에 물리적인

2021-07-25 06:35 UTC, ggjae commented on contents/operating-system/README.md
> +프로세스의 모든 코드는 항상 필요하지 않기 때문에 ```필요한 부분만 메모리에 올림으로써 메모리에 올라가는 프로세스의 크기를 줄인다.```
제가 정확하게 몰라서 그런데 '필요한 부분만 메모리에 올림으로써 메모리에 올라가는 프로세스의 크기를 줄인다'는 가상메모리의 역할이 아니고 밑에 작성하신 Demand-paging 방식중의 하나 아닌가요?

2021-07-25 06:35 UTC, ggjae commented on contents/operating-system/README.md
> +  * 이해하지 쉽고, 프로그래밍도 쉽다.
이해하기

2021-07-25 06:35 UTC, ggjae commented on contents/operating-system/README.md
> +  * 오래된 페이지가 항상 불필요하지 않은 정보를 포함하지 않을 수 있다.
말이 조금 어렵습니다 (__)

2021-07-25 06:42 UTC, Hee-Jae commented on contents/operating-system/README.md
> +  * 이해하지 쉽고, 프로그래밍도 쉽다.
이 부분은 제가 발견해서 오타 수정하고 새로 커밋했습니다.

2021-07-25 06:43 UTC, ggjae commented on contents/operating-system/README.md
> +  * 이해하지 쉽고, 프로그래밍도 쉽다.
우와. 희재님이 바꾸실 수 있나요? 신기하네요. 희재님 저 '코루틴'에 대해 작성하고 싶은데 어디 종류에 넣으면 좋을까요?

2021-07-25 07:33 UTC, Seogeurim commented on contents/operating-system/README.md
> +프로세스의 모든 코드는 항상 필요하지 않기 때문에 ```필요한 부분만 메모리에 올림으로써 메모리에 올라가는 프로세스의 크기를 줄인다.```
저도 그렇게 공부했었습니다! 지난번 OS 스터디 준비할 때 여러 자료들 참고하면서도 두 가지 개념이 혼재되어 소개있는 자료를 많이 봤는데, 이번 기회에 이 부분에 대해 확실한 답변을 알고 싶네요 !! 

그리고 인라인으로 코드 블락을 만들고 싶을 땐 백틱을 하나만 사용해도 된답니다 !!

2021-07-25 07:40 UTC, Seogeurim commented on contents/operating-system/README.md
> +  * 오래된 페이지가 항상 불필요하지 않은 정보를 포함하지 않을 수 있다.
저도 조금 어렵습니다 !! 수정되면 좋을 것 같아요 !

2021-07-25 07:43 UTC, Seogeurim reviewed
잘 읽었습니다 !! ㅎㅎ 오랜만에 가상메모리&페이지 교체 알고리즘의 개념을 다시 훑어볼 수 있는 기회가 되었네요 ㅎㅎ 앞서 재용님이 짚어주신 부분만 수정되면 좋을 것 같습니다 ~! 👍🏻👍🏻

2021-07-25 07:56 UTC, Hee-Jae commented on contents/operating-system/README.md
> +  * 이해하지 쉽고, 프로그래밍도 쉽다.
글쎄요... 저도 '코루틴'이라는 것을 지금 처음 들어봤는데 검색해 보니까 어디 분야에 소속 시키기가 굉장히 애매하네요. 다음 스터디 시간에 회의 해봅시다.

2021-07-25 08:17 UTC, wntjq68 approved these changes
가상메모리 개념 잘 복습하고 갑니다~ Belady의 모순 분명 많이 들은 말인데 또 까먹었네요 나중에 제가 정리 해서 올려야겠어요~

2021-07-25 08:27 UTC, Hee-Jae commented on contents/operating-system/README.md
> +  * 오래된 페이지가 항상 불필요하지 않은 정보를 포함하지 않을 수 있다.
FIFO 페이지 교체 알고리즘 특성상 **가장 오래된 페이지**가 Swap out 되어 빠져 나가게 됩니다. 페이지 교체를 가장 효율적으로 하기 위해서는 불필요한 정보를 포함하고 있는 페이지를 내보내야 합니다. 그러나 **가장 오래된 페이지**라고 해서 꼭 불필요한 정보를 포함하고 있다고 보장 되지는 않습니다. 따라서 위와 같은 효율성을 보장할 수는 없다는 내용입니다.
예를 들면 초기에 페이지에 적재된 변수가 중요한 정보를 가지고 있었는데, 가장 오래된 페이지라는 이유로 이 변수를 내보낸다고 해도 이 변수는 중요한 정보를 가지고 있는 만큼 자주 조회가 될 것이기 때문에 결국엔 곧 다시 불러와질 것입니다. 이런 경우 FIFO 알고리즘의 효율성은 떨어지게 됩니다.

2021-07-25 08:28 UTC, Hee-Jae approved these changes
가상메모리에 대해 잊어버리게 될 때쯤 이런 글을 올려주셔서 다시 머릿속에 되새기게 되었어요. 잘 봤습니다^^

2021-07-25 10:02 UTC, yoongoing commented on contents/operating-system/README.md
> +메인 메모리의 크기가 한정되어 있기때문에, 물리적인 메모리 크기보다 큰 프로세스를 실행시킬 수 없다. 그렇다면 메인 메모리보다 크기가 큰 프로세스를 실행시키고 싶으면 어떻게 해야 할까? 그래서 나온 방법이 바로 '가상메모리'이다.
수정하겠습니다!

2021-07-25 10:03 UTC, yoongoing commented on contents/operating-system/README.md
> +프로세스의 모든 코드는 항상 필요하지 않기 때문에 ```필요한 부분만 메모리에 올림으로써 메모리에 올라가는 프로세스의 크기를 줄인다.```
+ 그림, 재용 
오 찾아보니
프로세스 전체가 메모리 내에 올라오지 않더라고 실행히 가능하도록 하는 기법을 통틀어 가상메모리라고 하고,
필요한 부분만 메모리에 올림으로써 메모리에 올라가는 프로세스의 크기를 줄이는 방법을 요구 페이징이라고 하네요.

+ 그림 
참고하겠습니다!

2021-07-25 10:04 UTC, yoongoing commented on contents/operating-system/README.md
> +  * 이해하지 쉽고, 프로그래밍도 쉽다.
엌ㅋㅋ 바쁜 저를 대신하여 수정해주셔서 감사드립니다:)

2021-07-25 10:05 UTC, yoongoing commented on contents/operating-system/README.md
> +  * 오래된 페이지가 항상 불필요하지 않은 정보를 포함하지 않을 수 있다.
* 오래된 페이지가 불필요하지 않은 정보를 포함하지 않을 수 있다 => 오래된 페이지가 불필요한 정보를 포함한다고 보장할 수 없다.
로 수정하겠습니다.

제가 왜 저렇게 적었을까요

2021-07-25 13:29 UTC, KimKwon approved these changes
커밋 내역에서 노고의 흔적이 보이네요.
OS란 볼 땐 이해했다가도 다시 보면 헷갈리고 어려운 그런 존재죠.
고생하셨습니다 👍

2021-07-26 10:06 UTC, ggjae commented on contents/operating-system/README.md
> +프로세스의 모든 코드는 항상 필요하지 않기 때문에 ```필요한 부분만 메모리에 올림으로써 메모리에 올라가는 프로세스의 크기를 줄인다.```
있기때문에를 있기 때문에로 수정해주실 수 있나요?

2021-07-26 10:08 UTC, ggjae commented on contents/operating-system/README.md
> +프로세스의 모든 코드는 항상 필요하지 않기 때문에 ```필요한 부분만 메모리에 올림으로써 메모리에 올라가는 프로세스의 크기를 줄인다.```
아아. 커밋 전 게시물이 review되어 혼란에 빠졌습니다 죄송해요 :)

2021-07-26 10:09 UTC, ggjae approved these changes
고생하셨어요 :)

2021-07-26 18:48 UTC, Seogeurim approved these changes

2021-07-26 18:48 UTC, merged