Database/yoongoing
Seogeurim/CS-study pull request #64
Opened 2021-08-08 03:04 UTC by yoongoing

### 변경 사항  
1. 데이터베이스 정규화
> Issue 참고 : [Note Status Check](https://github.com/Seogeurim/CS-study/issues/2)

### Point of discussion 
1. 오타, 잘못된 내용, 이해안가는 점 비판 지적 환영입니다~

### Reference 
리드미에 기재했습니다.

2021-08-08 10:45 UTC, Hee-Jae commented on contents/database/README.md
> +다치 종속 : 속성 A -> (속성 B, 속성 C) 일때, A->B를 만족하고, **B와 C가 무관**할때 B는 A에 다치종속 관계하고 하며, A->>B 라고 한다.
`다치종속 관계하고 하며` 오타 발견했습니다! 그리고 `B와 C가 무관` 부분 bold 처리를 의도하신거 같은데 적용이 안됐네요

2021-08-08 10:45 UTC, Hee-Jae commented on contents/database/README.md
> +다치 종속 : 속성 A -> (속성 B, 속성 C) 일때, A->B를 만족하고, **B와 C가 무관**할때 B는 A에 다치종속 관계하고 하며, A->>B 라고 한다.
다치종속 관계가 있으면 어떤 문제가 발생할 수 있는지, 다치종속 관계는 어떻게 제거할 수 있는지 궁금합니다

2021-08-08 15:33 UTC, yoongoing commented on contents/database/README.md
> +다치 종속 : 속성 A -> (속성 B, 속성 C) 일때, A->B를 만족하고, **B와 C가 무관**할때 B는 A에 다치종속 관계하고 하며, A->>B 라고 한다.
헉 수정하겠습니다!

2021-08-09 08:15 UTC, ggjae requested changes
항상 제2 정규형의 함수적 종속과 제3 정규형의 이행적 함수종속이 사용하는 단어가 비슷하여 어렵게 생각하였는데 이번 PR을 통하여 지식 하나 더 얻고 갑니다 :) 
문맥이 안맞는 단어 한 줄만 Request 보내놓았습니다!

2021-08-09 08:15 UTC, ggjae commented on contents/database/README.md
> +정규화란 **함수의 종속성 이론**을 통해 데이터의 중복성을 최소화하고 일관성 등을 보장하여 데이터베이스의 품질을 보장하고 성능의 향상해나가는 과정이다. 정규화 수준이 높을수록 유연한 데이터 구축이 가능하고 데이터의 정확성이 높아지는 반면, 물리적 접근이 복잡하고 너무 많은 조인으로 인해 조회 성능이 저하된다는 특징이 있다
`품질을 보장하고 성능의 향상해나가는 과정이다.` 라는 말이 문맥상 오류가 있는 것 같아요! :)

2021-08-09 13:59 UTC, wntjq68 approved these changes
정규화 데이터베이스에서 필수적인 부분이죠 ㅎㅎ 나중에 좀 더 이해를 돕기 위해 예시 테이블을 몇개 추가하면 더 좋을거 같아요 ! (내가할까,,,)

2021-08-13 04:21 UTC, yoongoing commented on contents/database/README.md
> +다치 종속 : 속성 A -> (속성 B, 속성 C) 일때, A->B를 만족하고, **B와 C가 무관**할때 B는 A에 다치종속 관계하고 하며, A->>B 라고 한다.
위의 예시에서는A->>B 일때, C값이 중복될수 있답니다.
예를들어

(회원번호)-> (이름, 주문번호) 인 테이블에서 
(회원번호 ->> 주문번호) 일때, 

정희재란 고객이 책을 두번 주문하면 정희재 이름이 불필요하게 두번 중복됩니다.
이를 해결하기 위해서는 (회원번호->이름), (회원번호->주문번호)로 쪼개주는것이죠

이 예시 넣어놓겠습니다

2021-08-13 04:22 UTC, yoongoing commented on contents/database/README.md
> +정규화란 **함수의 종속성 이론**을 통해 데이터의 중복성을 최소화하고 일관성 등을 보장하여 데이터베이스의 품질을 보장하고 성능의 향상해나가는 과정이다. 정규화 수준이 높을수록 유연한 데이터 구축이 가능하고 데이터의 정확성이 높아지는 반면, 물리적 접근이 복잡하고 너무 많은 조인으로 인해 조회 성능이 저하된다는 특징이 있다
수정해놓겠습니다~

2021-08-13 04:46 UTC, KimKwon approved these changes
정규화 쉽게 외우는 법!! 하면서 `도부이결다조` 로 외웠던 것들이네요
정리 감사합니다 💯

2021-08-14 08:15 UTC, Hee-Jae commented on contents/database/README.md
> +다치 종속 : 속성 A -> (속성 B, 속성 C) 일때, A->B를 만족하고, **B와 C가 무관**할때 B는 A에 다치종속 관계하고 하며, A->>B 라고 한다.
쪼개 버리면 되는거였군요! 간단하네요

2021-08-14 08:16 UTC, Hee-Jae approved these changes

2021-08-14 10:39 UTC, Seogeurim reviewed
데이터베이스 정규화에는 모르는 용어들이 많아서 볼 때마다 어렵네요 !! 깔끔히 정리해주셔서 감사합니다 !! ㅎㅎ

2021-08-14 10:39 UTC, Seogeurim commented on contents/database/README.md
> +릴레이션에 속한 모든 도메인이 원자값만으로 되어있는 정규형이다
INF -> 1NF인 것 같네요!

2021-08-14 10:39 UTC, Seogeurim commented on contents/database/README.md
> +```
각 종속 관계를 `왜 제거해야 하는지`에 대한 설명이 추가되면 좋을 것 같아요 !!

2021-08-14 10:39 UTC, Seogeurim commented on contents/database/README.md
> +다시 조인하면 예상하지 못했던 튜플들이 생성되는 경우가 발생한다.
예를 들면 어떤 경우인지 알 수 있을까요?

2021-08-14 10:39 UTC, Seogeurim commented on contents/database/README.md
> +모든 조인 종속이 릴레이션의 후보키를 통해서만 성립되는 정규형이다.
조인 종속이 릴레이션의 후보키를 통해서만 성립된다는 것이 무슨 말인가요?

2021-08-15 11:51 UTC, yoongoing commented on contents/database/README.md
> +릴레이션에 속한 모든 도메인이 원자값만으로 되어있는 정규형이다
수정해놓겠습니다!

2021-08-15 11:54 UTC, yoongoing commented on contents/database/README.md
> +```
모든 종속은 이상값을 최소화하고 제거하기 위함인데 추가해놓겠습니다!

2021-08-15 12:33 UTC, yoongoing commented on contents/database/README.md
> +다시 조인하면 예상하지 못했던 튜플들이 생성되는 경우가 발생한다.
A   B   C 
ㅡㅡㅡㅡㅡ
s1  p1  c2 
s1  p2  c1 
s2  p1  c1 
s1  p1  c1 

이 테이블의 경우[A,B] [B,C] [A,C] 로 쪼갤때 아래와 같습니다

A    B                    
ㅡㅡㅡ                   
s1  p1          
s1  p2         
s2  p1          
                    
B    C        
ㅡㅡㅡ   
p1  c2       
p2  c1      
p1  c1      

A   D
ㅡㅡㅡ
s1  c2
s1  c1
s2  c1                
                                  
[A,B]+[B,C]+[A,C] 다시 조인하면

 A   B   C
ㅡㅡㅡㅡㅡ
s1  p1  c2
s1  p1  c1
s1  p2  c1
s2   p1 c2  ===> 이상값 발견!
s2  p1  c1

이런 이상 상황을 없애기 위해 제 5정규형을 시행합니다. 적분상수를 떠올리시면 편할 것 같아요!
@Seogeurim

2021-08-15 12:33 UTC, yoongoing commented on contents/database/README.md
> +모든 조인 종속이 릴레이션의 후보키를 통해서만 성립되는 정규형이다.
릴레이션 R의 모든 조인종속이 R의 후보키를 통해서만 성립되는 정규형이라고 수정해놓겠습니다!
말그대로 릴레이션 R의 조인종속이 후보키를 통해서만 성립될때 5정규형을 만족한다고 합니다.
5정규형을 만족할때 쪼개었다가 합쳐도 이상이 없다고 합니다.

2021-08-23 16:40 UTC, Seogeurim commented on contents/database/README.md
> +다시 조인하면 예상하지 못했던 튜플들이 생성되는 경우가 발생한다.
오 !!! 오 !! 신기하네요 바아로 이해됐습니당 !! 감사합니다 ~!!

2021-09-03 16:14 UTC, Seogeurim approved these changes

2021-09-04 07:03 UTC, ggjae approved these changes

2021-09-04 07:04 UTC, merged