Database/yoongoing
Seogeurim/CS-study pull request #69
Opened 2021-08-15 13:28 UTC by yoongoing

### 변경 사항  
1. 정규화

> Issue 참고 : [Note Status Check](https://github.com/Seogeurim/CS-study/issues/2)

### Point of discussion 

비판 지적 환영합니다!

### Reference

2021-08-16 06:58 UTC, ggjae requested changes
... 그런 방 아닙니다

2021-08-16 06:58 UTC, ggjae commented on contents/database/README.md
> +정규화란 **함수의 종속성 이론**을 통해 데이터의 중복성을 최소화하고 일관성 등을 보장하여 데이터베이스의 품질과 성능을 향상키시는 과정이다. 정규화 수준이 높을수록 유연한 데이터 구축이 가능하고 데이터의 정확성이 높아지는 반면, 물리적 접근이 복잡하고 너무 많은 조인으로 인해 조회 성능이 저하된다는 특징이 있다
KISSY...?

2021-08-20 12:59 UTC, Hee-Jae reviewed
예시를 흐쟈미라는 흔하지 않은 예시로 들어주셨네요ㅎㅎ

2021-08-20 12:59 UTC, Hee-Jae commented on contents/database/README.md
> +* 반정규화 방법에는 테이블 통합, 테이블 분할, 중복 데이블 추가, 중복 송성 추가 등이 있다.
`중복 송성` 오타 발견했습니다.

2021-08-20 12:59 UTC, Hee-Jae commented on contents/database/README.md
> +    * `갱신위주의 속성 분할` : 데이터 갱신 시 레코드 잠금으로 인해 다른 작업을 수행 할 수 없으므로 갱신이 자주 일어나느 속성들을 수직 분할하여 사용한다.
`갱신이 자주 일어나느` 오타 발견했습니다.

2021-08-20 12:59 UTC, Hee-Jae commented on contents/database/README.md
> +    * `보안을 적용해야 하는 속성 분할` : 데이블 내의 특정 속성에 대해 보안을 적용할 수 없으므로 보안을 적용해야 하는 속성들을 수직분할 하여 사용한다.
`데이블` 오타 발견했습니다.

2021-08-20 12:59 UTC, Hee-Jae commented on contents/database/README.md
> +    * 데이블 중복과 속성의 중복을 고려한다.
`데이블` 오타 발견했습니다.

2021-08-20 12:59 UTC, Hee-Jae commented on contents/database/README.md
> +    * 기본키의 형태가 적절하지 않거나 여러 개의 속성으로 구성된 경우
기본키의 형태가 적절하지 않거나 여러 개의 속성으로 구성된 경우에 중복 속성을 추가함으로써 어떻게 개선할 수 있는지 궁금합니다.

2021-09-04 07:03 UTC, ggjae approved these changes

2021-09-04 07:04 UTC, merged